### ISSUE TITLE
confused about 2 blog themes

### ISSUE THREAD

**Issue by vnugent** [gatsbyjs/gatsby-starter-blog-theme#10]
what is the difference between this repo and the gatsby-theme-blog-core? https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-theme-blog-core#readme

Which one is suitable for building new themes?

**Comment by Scot3004** [comment]
gatsby-theme-blog-core includes only the logic to make a blog and this one inherits from it and adds some styles and is suitable to use as is, the other one renders a json list
