### ISSUE TITLE
gatsby-plugin-theme-ui folder in wrong location

### ISSUE THREAD

**Issue by Amorpheuz** [gatsbyjs/gatsby-starter-blog-theme#16]
## Description

Theme ui shadowing is broken in starter template, as the folder is located in the wrong location. The [Style Specific Migration Notes - gatsby-theme-blog](https://github.com/gatsbyjs/themes/tree/master/packages/gatsby-theme-blog#style-specific-migration-notes) indicate that the folder `gatsby-plugin-theme-ui` shouldn't be nested inside the gatsby-theme-blog directory. It needs to be at the root level.

Upon the cloning the starter from [New Site | gatsby-theme-blog](https://github.com/gatsbyjs/themes/tree/master/packages/gatsby-theme-blog#for-a-new-site) via:
```shell
gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
```
I encountered similar behavior where the three default values defined in the default file (indicated below) didn't have any effect.
https://github.com/gatsbyjs/gatsby-starter-blog-theme/blob/4cf8cdafbb882e4a04daa59fe9c61e022f1e2eb2/src/gatsby-theme-blog/gatsby-plugin-theme-ui/index.js#L1-L17

Moving the folder outside `gatsby-theme-blog` into the `src` folder solved the issue.

### Steps to reproduce

1. Create starter with: `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`.
2. `cd` into the folder and run development server with `gatsby develop`.
3. Open `localhost:8000`.
4. The color of the Blog post links will be purple (easiest to notice), despite the `gatsby-plugin-theme-ui/index.js` having overridden them to `darkBlue` under primary.

### Expected result

The link colors should have be blue, since the colors have been overridden:
![image](https://user-images.githubusercontent.com/22113778/87223057-4dbe0c00-c397-11ea-97d3-9d32c4e56c09.png)

### Actual result

The colors are purple:
![image](https://user-images.githubusercontent.com/22113778/87223045-341cc480-c397-11ea-82dc-ef2f390421e1.png)

### Environment

System:
- OS: Windows 10 10.0.19041
- CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

Binaries:
- Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
- Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
- npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD

Languages:
- Python: 3.8.3

Browsers:
- Edge: 83.0.478.61 (cli printed: 44.19041.1.0)

npmPackages:
- gatsby: ^2.24.2 => 2.24.2
- gatsby-theme-blog: ^2.0.0 => 2.0.0
- gatsby-theme-blog-darkmode: ^2.0.0 => 2.0.0

npmGlobalPackages:
- gatsby-cli: 2.12.60

**Comment by mdovn** [comment]
That’s right. It took me a whole night to figure it out 🤦

**Comment by aaaakshat** [comment]
Yep, #17 addresses this issue, but a core team member needs to review and merge the PR.
