### ISSUE TITLE
Images added to posts with markdown syntax not rendered

### ISSUE THREAD

**Issue by inakicalvo** [gatsbyjs/gatsby-starter-blog-theme#20]
Hi there!

I've created a new site using this starter. The site runs properly when I execute `gatsby develop` and new posts get rendered into the front-end. The problem is that I can't add images to the posts using regular markdown syntax.

I've just created a new site and added this line to the body of the post: `![beach](./sunset-beach.jpg)` in the index.mdx file of the Hello world post (this was **the only change** made). But the image is not displayed on the front-end within the body of the post; although it gets displayed as the featured image.

When using an image hosted somewhere else it gets displayed, for example: `![beach](https://images.unsplash.com/photo-1598450853508-eee0a3a4fb85?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=625&q=80)`.

Here is more info about my development environment:

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 3.7.5 - /Users/inakicalvo/opt/anaconda3/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.50 => 2.24.50
    gatsby-theme-blog: ^2.0.1 => 2.0.1
  npmGlobalPackages:
    gatsby-cli: 2.12.89

```
I don't have this problem with the [old blog starter](https://github.com/gatsbyjs/gatsby-starter-blog) so I'm wondering if it might be a bug.

**Comment by laurieontech** [comment]
Thanks for the PR! This is actually unrelated to the starter and a clash with the most recent version of MDX that's being included.

In order to get around it, for now, you can add `resolutions` to your package.json file to ensure it's using the working version of MDX packages.

```
  "resolutions": {
    "@mdx-js/mdx": "1.6.16",
    "@mdx-js/react": "1.6.16",
    "@theme-ui/core": "0.4.0-rc.1",
    "@theme-ui/css": "0.4.0-rc.1",
    "@theme-ui/mdx": "0.4.0-rc.1"
  }
```

Resolutions work best when using yarn.

We'll work on getting it fixed in the larger project and hope to have everything squared away soon!

**Comment by inakicalvo** [comment]
@laurieontech thanks a lot! Your tip helped me fixed it. 

I created another site using Yarn as the package manager, and added the resolutions you suggested.

And now adding markdown images to posts works as expected!

Thanks again.

**Comment by laurieontech** [comment]
Glad to hear it!
