### ISSUE TITLE
Error: [useColorMode] requires the ThemeProvider component

### ISSUE THREAD

**Issue by devjefe** [gatsbyjs/gatsby-starter-blog-theme#3]
Second time I've done a fresh install of the starter and started receiving: Error: [useColorMode] requires the ThemeProvider component. Do I need to bring in ThemeProvider?

The only  changes I've made to the starter application are:
1) Uncommented colors.js
2) Changed metadata
3) Installed notes theme and added to gatsby config.

**Comment by third774** [comment]
I also ran into this issue after running `yarn add gatsby-theme-notes` then adding the following to `gatsby-config.js`:

```js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-theme-blog`,
      options: {},
    },
    {
      resolve: `gatsby-theme-notes`,
      options: {
        // basePath defaults to `/`
        basePath: `/notes`,
      },
    },
  ],
  // ...
}
```

**Comment by CanRau** [comment]
@devjefe @third774 could you guys solve that issue? just ran into it as well not sure what change or when it occurred 🤷‍♂️my fault as I didn't commit often enough 🤦🏻‍♂️
Disabling `gatsby-plugin-theme-ui` & copying its `wrapRootElement` functions in my local files resolves the error mentioned yet not all styles are being applied and I'm not sure which ones 🤔

By the way I'm not using `gatsby-theme-blog` but `gatsby-plugin-theme-ui` directly

**Comment by AnNiket07** [comment]
Is there a solution for this problem ..because i am still  facing this issue  and can't understand how to solve it...

**Comment by fedorareis** [comment]
I just tried to start using the plugin and am also running into this issue. Everything works fine until I add this specific plugin. I already have `gatsby-plugin-theme-ui` on my site.
